"""AnalysisPlan — determines which engines to run and in what order."""

from pydantic import BaseModel, Field

from codeguardian.core.context import ScanContext

VALID_DIMENSIONS = [
    "scale",
    "complexity",
    "maintainability",
    "defects",
    "security",
    "performance",
    "testing",
    "evolution",
    "architecture",
]



DIMENSION_ENGINE_MAP: dict[str, tuple[str, ...]] = {
    "scale": ("structure", "metrics"),
    "complexity": ("complexity",),
    "maintainability": ("complexity", "oo_design"),
    "architecture": ("structure", "metrics", "complexity", "git", "oo_design", "dependency"),
    "defect": ("defect", "cross_function"),
    "defects": ("defect", "cross_function"),
    "security": ("security",),
    "performance": ("performance",),
    "testing": ("testing",),
    "evolution": ("git",),
    "config": ("config_risk",),
    "deployment": ("config_risk",),
    "design": ("oo_design",),
}


STANDARD_ENABLED_ENGINES = ["structure", "metrics", "complexity", "defect", "security", "performance", "testing", "git", "oo_design", "dependency", "cross_function"]
QUICK_ENABLED_ENGINES = ["structure", "metrics", "defect", "performance", "testing"]


DEEP_ENABLED_ENGINES = STANDARD_ENABLED_ENGINES.copy()


# Engines that are NOT enabled by default and must be explicitly opted-in via
# --dimensions (config / deployment / security). config_risk is the only current
# member: its domain is configuration files (yaml/toml/env/Dockerfile), which the
# default profile deliberately avoids scanning to cut low-signal findings on
# non-code assets (package-lock.json, i18n bundles, fixtures, schemas, ...).
OPT_IN_ENGINES = frozenset({"config_risk"})


class AnalysisPlan(BaseModel):
    """Execution plan generated by the Planner based on project characteristics."""

    enabled_engines: list[str] = Field(default_factory=lambda: STANDARD_ENABLED_ENGINES.copy())
    engine_order: list[str] | None = None  # If set, run engines in this order
    target_files: list[str] = Field(default_factory=list)  # Empty = auto-discover
    target_modules: list[str] = Field(default_factory=list)
    enabled_dimensions: list[str] | None = None  # If set, filter to specific dimensions
    concurrency_limit: int = 4  # Max parallel engine tasks
    coverage_mode: str = "auto"  # auto / file / disabled
    git_mode: str = "auto"  # auto / full / disabled
    ai_tasks: list[dict[str, object]] = Field(default_factory=list)



def normalize_dimensions(dimensions: list[str] | None) -> list[str]:
    """Normalize user-provided dimension names."""
    if not dimensions:
        return []
    normalized = [item.strip().lower() for item in dimensions if item.strip()]
    if "all" in normalized:
        return VALID_DIMENSIONS.copy()
    return normalized



def find_unsupported_dimensions(dimensions: list[str] | None) -> list[str]:
    """Return requested dimensions that do not map to any executable engine."""
    normalized = normalize_dimensions(dimensions)
    return [dimension for dimension in normalized if dimension not in DIMENSION_ENGINE_MAP]


def build_plan(ctx: ScanContext) -> AnalysisPlan:
    """Build an analysis plan based on the scan context."""
    plan = AnalysisPlan()

    if ctx.is_quick:
        plan.enabled_engines = QUICK_ENABLED_ENGINES.copy()
        plan.concurrency_limit = 2
    elif ctx.is_deep:
        plan.enabled_engines = DEEP_ENABLED_ENGINES.copy()
        plan.concurrency_limit = 6

    normalized_dimensions = normalize_dimensions(ctx.dimensions)
    if normalized_dimensions:
        unsupported = find_unsupported_dimensions(normalized_dimensions)
        if unsupported:
            raise ValueError(
                "Unsupported dimensions requested: "
                f"{', '.join(sorted(set(unsupported)))}. "
                f"Supported: {', '.join(VALID_DIMENSIONS)}"
            )

        plan.enabled_dimensions = normalized_dimensions
        allowed_engines = {
            engine
            for dimension in normalized_dimensions
            for engine in DIMENSION_ENGINE_MAP.get(dimension, ())
        }
        # Opt-in engines (e.g. config_risk) are excluded from default profiles but
        # should run when a requested dimension explicitly maps to them.
        opt_in_requested = allowed_engines & OPT_IN_ENGINES
        base_engines = list(plan.enabled_engines) + [
            engine for engine in opt_in_requested if engine not in plan.enabled_engines
        ]
        plan.enabled_engines = [engine for engine in base_engines if engine in allowed_engines]

    if ctx.target_files:
        plan.target_files = ctx.target_files.copy()
        plan.coverage_mode = "file"
    if ctx.incremental:
        plan.git_mode = "diff"

    # Semgrep opt-in: only activate when explicitly enabled in config AND
    # the security dimension is in scope (or no dimension filter is applied).
    if ctx.config.semgrep.enabled:
        security_in_scope = (
            plan.enabled_dimensions is None
            or "security" in plan.enabled_dimensions
        )
        if security_in_scope and "semgrep" not in plan.enabled_engines:
            plan.enabled_engines.append("semgrep")

    return plan

