"""Tests for MetricsEngine project metrics."""

from pathlib import Path
from tempfile import TemporaryDirectory

from codeguardian.config.loader import load_app_config
from codeguardian.core.context import ScanContext
from codeguardian.engines.metrics_engine import MetricsEngine
from codeguardian.models.metric import MetricNames


async def test_metrics_engine_reports_duplication_rate_for_repeated_blocks() -> None:
    repeated_block = """
def build_payload(user_id, status):
    payload = {
        \"user_id\": user_id,
        \"status\": status,
    }
    if status == \"active\":
        return payload
    return {\"archived\": payload}
""".strip()

    with TemporaryDirectory() as tmpdir:
        root = Path(tmpdir)
        (root / "a.py").write_text(repeated_block + "\n", encoding="utf-8")
        (root / "b.py").write_text(repeated_block + "\n", encoding="utf-8")
        (root / "unique.py").write_text("def ping():\n    return 'ok'\n", encoding="utf-8")

        ctx = ScanContext(project_root=str(root), config=load_app_config(None))
        result = await MetricsEngine().analyze(ctx)

        project_metrics = {
            metric.metric_name: metric
            for metric in result.metrics
            if metric.target_id == "project"
        }

        assert project_metrics[MetricNames.FILE_COUNT].value == 3.0
        assert project_metrics[MetricNames.DUPLICATION_RATE].value > 0.0


async def test_metrics_engine_reports_zero_duplication_for_unique_files() -> None:
    with TemporaryDirectory() as tmpdir:
        root = Path(tmpdir)
        (root / "a.py").write_text("def one():\n    return 1\n", encoding="utf-8")
        (root / "b.py").write_text("def two():\n    return 2\n", encoding="utf-8")

        ctx = ScanContext(project_root=str(root), config=load_app_config(None))
        result = await MetricsEngine().analyze(ctx)

        project_metrics = {
            metric.metric_name: metric
            for metric in result.metrics
            if metric.target_id == "project"
        }

        assert project_metrics[MetricNames.DUPLICATION_RATE].value == 0.0


async def test_metrics_engine_excludes_generated_sources_from_file_counts() -> None:
    generated_proto = """
// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: demo.proto

package demo;

public final class DemoProto {
  private DemoProto() {}
}
"""

    with TemporaryDirectory() as tmpdir:
        root = Path(tmpdir)
        (root / "kept.py").write_text("def keep():\n    return True\n", encoding="utf-8")
        target = root / "app" / "src" / "main" / "java" / "demo" / "pb" / "DemoProto.java"
        target.parent.mkdir(parents=True, exist_ok=True)
        target.write_text(generated_proto.strip() + "\n", encoding="utf-8")

        ctx = ScanContext(project_root=str(root), config=load_app_config(None))
        result = await MetricsEngine().analyze(ctx)

        project_metrics = {
            metric.metric_name: metric
            for metric in result.metrics
            if metric.target_id == "project"
        }
        language_counts = {
            metric.target_id: metric.value
            for metric in result.metrics
            if metric.target_type == "language"
        }

        assert project_metrics[MetricNames.FILE_COUNT].value == 1.0
        assert language_counts == {"python": 1.0}

