"""Tests for ignore helpers and generated-source detection."""

from pathlib import Path
from tempfile import TemporaryDirectory

from codeguardian.utils.ignore import should_ignore


def test_should_ignore_generated_directory_sources() -> None:
    with TemporaryDirectory() as tmpdir:
        root = Path(tmpdir)
        target = root / "generated" / "demo" / "Sample.java"
        target.parent.mkdir(parents=True, exist_ok=True)
        target.write_text("class Sample {}\n", encoding="utf-8")

        assert should_ignore(target) is True


def test_should_ignore_protobuf_generated_source_headers() -> None:
    generated_proto = """
// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: demo.proto

package demo;

public final class DemoProto {
  private DemoProto() {}
}
"""

    with TemporaryDirectory() as tmpdir:
        root = Path(tmpdir)
        target = root / "app" / "src" / "main" / "java" / "demo" / "pb" / "DemoProto.java"
        target.parent.mkdir(parents=True, exist_ok=True)
        target.write_text(generated_proto.strip() + "\n", encoding="utf-8")

        assert should_ignore(target) is True


def test_should_not_ignore_regular_source_files() -> None:
    with TemporaryDirectory() as tmpdir:
        root = Path(tmpdir)
        target = root / "src" / "main" / "java" / "demo" / "Service.java"
        target.parent.mkdir(parents=True, exist_ok=True)
        target.write_text("class Service { boolean getSubsystem() { return true; } }\n", encoding="utf-8")

        assert should_ignore(target) is False


def test_should_ignore_jdk_system_files() -> None:
    """JDK system files like jdk/demo/nio/zipfs/Demo.java must be excluded."""
    with TemporaryDirectory() as tmpdir:
        root = Path(tmpdir)
        target = root / "jdk" / "demo" / "nio" / "zipfs" / "Demo.java"
        target.parent.mkdir(parents=True, exist_ok=True)
        target.write_text("class Demo {}\n", encoding="utf-8")

        assert should_ignore(target) is True


def test_should_ignore_versioned_jdk_directory() -> None:
    """Versioned JDK paths like jdk-17/lib/src.zip should be excluded."""
    with TemporaryDirectory() as tmpdir:
        root = Path(tmpdir)
        target = root / "jdk-17" / "lib" / "Server.java"
        target.parent.mkdir(parents=True, exist_ok=True)
        target.write_text("class Server {}\n", encoding="utf-8")

        assert should_ignore(target) is True


def test_should_ignore_jre_directory() -> None:
    with TemporaryDirectory() as tmpdir:
        root = Path(tmpdir)
        target = root / "jre1.8.0_371" / "lib" / "Utils.java"
        target.parent.mkdir(parents=True, exist_ok=True)
        target.write_text("class Utils {}\n", encoding="utf-8")

        assert should_ignore(target) is True


def test_should_ignore_sdk_directory() -> None:
    with TemporaryDirectory() as tmpdir:
        root = Path(tmpdir)
        target = root / "sdk" / "platforms" / "android" / "Helper.java"
        target.parent.mkdir(parents=True, exist_ok=True)
        target.write_text("class Helper {}\n", encoding="utf-8")

        assert should_ignore(target) is True


def test_should_ignore_non_code_text_files() -> None:
    """Docs / static assets / templates / IDL are hard-excluded from all engines."""
    non_code_samples = [
        "README.md",
        "notes.rst",
        "data.csv",
        "metrics.tsv",
        "index.html",
        "app.css",
        "theme.scss",
        "api.proto",
        "schema.graphql",
        "service.thrift",
        "page.tmpl",
        "email.hbs",
        "layout.jinja2",
    ]
    with TemporaryDirectory() as tmpdir:
        root = Path(tmpdir)
        for name in non_code_samples:
            target = root / name
            target.write_text("x\n", encoding="utf-8")
            assert should_ignore(target) is True, f"{name} should be ignored"


def test_should_not_ignore_config_files_directly() -> None:
    """Config files are not hard-excluded at the ignore layer.

    They are only scanned when config_risk engine is explicitly opted in via
    --dimensions config / security. Default engines never receive them because
    no engine declares these suffixes in its SUPPORTED_EXTENSIONS.
    """
    config_samples = ["app.yaml", "app.toml", "config.json", ".env", "Dockerfile"]
    with TemporaryDirectory() as tmpdir:
        root = Path(tmpdir)
        for name in config_samples:
            target = root / name
            target.write_text("x\n", encoding="utf-8")
            assert should_ignore(target) is False, f"{name} should NOT be hard-ignored"
