"""Tests for the AI Deep Review pipeline components."""

from __future__ import annotations

import json
from pathlib import Path
from unittest.mock import AsyncMock, MagicMock, patch

import pytest

from codeguardian.ai.deep_review.budget import TokenBudgetManager
from codeguardian.ai.deep_review.chunker import Chunker
from codeguardian.ai.deep_review.context_builder import ContextPackBuilder, load_custom_rules
from codeguardian.ai.deep_review.filter import CodeFilter, LOW_VALUE_FINDING_CATEGORIES
from codeguardian.ai.deep_review.merger import MergeOutput, ResultMerger
from codeguardian.ai.deep_review.models import (
    AIFindingRaw,
    CodeChunk,
    ContextPack,
    ReviewResult,
)
from codeguardian.ai.deep_review.pipeline import DeepReviewPipeline
from codeguardian.ai.deep_review.project_index import ProjectIndex
from codeguardian.ai.deep_review.reviewer import AIReviewer
from codeguardian.ai.prompts.deep_review import build_review_prompt
from codeguardian.config.loader import load_app_config
from codeguardian.config.schema import AIConfig, AppConfig, DeepReviewConfig
from codeguardian.core.context import ScanContext
from codeguardian.models.common import Location
from codeguardian.models.enums import Confidence, Severity
from codeguardian.models.evidence import AIReviewEvidence
from codeguardian.models.finding import Finding


# ---------------------------------------------------------------------------
# CodeFilter tests
# ---------------------------------------------------------------------------


class TestCodeFilter:
    def test_skip_generated_file(self):
        f = CodeFilter()
        assert f.should_skip_file("src/generated/model.java") is True
        assert f.should_skip_file("src/gen/proto.go") is True

    def test_skip_vendor_file(self):
        f = CodeFilter()
        assert f.should_skip_file("vendor/lib/util.go") is True
        assert f.should_skip_file("node_modules/pkg/index.js") is True

    def test_skip_test_file(self):
        f = CodeFilter()
        assert f.should_skip_file("src/tests/test_main.py") is True
        assert f.should_skip_file("app/util_test.go") is True

    def test_skip_config_file(self):
        f = CodeFilter()
        assert f.should_skip_file("config.json") is True
        assert f.should_skip_file("settings.yaml") is True

    def test_allow_normal_source(self):
        f = CodeFilter()
        assert f.should_skip_file("src/main/service/OrderService.java") is False
        assert f.should_skip_file("app/handler.go") is False

    def test_skip_by_content_marker(self):
        f = CodeFilter()
        assert f.should_skip_by_content("// Code generated by protoc\npackage proto\n") is True
        assert f.should_skip_by_content("@Generated\npublic class Model {") is True
        assert f.should_skip_by_content("package main\n\nfunc main() {") is False

    def test_skip_trivial_function(self):
        f = CodeFilter()
        assert f.should_skip_function(line_count=3, complexity=1, name="getName") is True
        assert f.should_skip_function(line_count=2, complexity=0, name="toString") is True
        assert f.should_skip_function(line_count=50, complexity=10, name="processOrder") is False

    def test_classify_priority_p0(self):
        f = CodeFilter()
        assert f.classify_priority(has_local_findings=True) == 0
        assert f.classify_priority(is_security_sensitive=True) == 0
        assert f.classify_priority(is_changed=True) == 0

    def test_classify_priority_p1(self):
        f = CodeFilter()
        assert f.classify_priority(complexity=15) == 1
        assert f.classify_priority(nesting_depth=5) == 1

    def test_classify_priority_p2(self):
        f = CodeFilter()
        assert f.classify_priority(complexity=10) == 2
        assert f.classify_priority(line_count=100) == 2
        assert f.classify_priority(has_todo=True) == 2


# ---------------------------------------------------------------------------
# CodeChunk & ContextPack tests
# ---------------------------------------------------------------------------


class TestCodeChunk:
    def test_estimate_tokens(self):
        chunk = CodeChunk(
            file_path="test.py",
            source_code="x = 1\n" * 100,
            language="python",
            line_start=1,
            line_end=100,
        )
        # 600 chars / 4 + 500 overhead = 650
        tokens = chunk.estimate_tokens()
        assert 600 <= tokens <= 700

    def test_default_priority(self):
        chunk = CodeChunk(
            file_path="f.py", source_code="pass", language="python",
            line_start=1, line_end=1,
        )
        assert chunk.priority == 2  # default P2


class TestContextPack:
    def test_build_dependency_section_empty(self):
        pack = ContextPack(target_code="code", file_path="f.py")
        assert pack.build_dependency_section() == "无外部依赖签名"

    def test_build_dependency_section_with_sigs(self):
        pack = ContextPack(
            target_code="code", file_path="f.py",
            dependency_signatures=["def foo() -> int", "def bar(x: str) -> None"],
        )
        section = pack.build_dependency_section()
        assert "def foo() -> int" in section
        assert "def bar(x: str) -> None" in section


# ---------------------------------------------------------------------------
# TokenBudgetManager tests
# ---------------------------------------------------------------------------


class TestTokenBudgetManager:
    def test_allocate_within_budget(self):
        budget = TokenBudgetManager(max_tokens=10000)
        chunks = [
            CodeChunk(file_path="a.py", source_code="x" * 400, language="python",
                      line_start=1, line_end=10, priority=0),
            CodeChunk(file_path="b.py", source_code="y" * 400, language="python",
                      line_start=1, line_end=10, priority=1),
        ]
        approved = budget.allocate(chunks)
        assert len(approved) == 2

    def test_allocate_exceeds_budget(self):
        budget = TokenBudgetManager(max_tokens=600)
        # Each chunk ~600 tokens, so only 1 should fit
        chunks = [
            CodeChunk(file_path="a.py", source_code="x" * 400, language="python",
                      line_start=1, line_end=10, priority=0),
            CodeChunk(file_path="b.py", source_code="y" * 400, language="python",
                      line_start=1, line_end=10, priority=1),
        ]
        approved = budget.allocate(chunks)
        assert len(approved) == 1

    def test_priority_ordering(self):
        budget = TokenBudgetManager(max_tokens=700)
        chunks = [
            CodeChunk(file_path="low.py", source_code="x" * 400, language="python",
                      line_start=1, line_end=10, priority=2),
            CodeChunk(file_path="high.py", source_code="y" * 400, language="python",
                      line_start=1, line_end=10, priority=0),
        ]
        approved = budget.allocate(chunks)
        assert len(approved) == 1
        assert approved[0].file_path == "high.py"  # P0 should be selected first

    def test_consume_tracks_spending(self):
        budget = TokenBudgetManager(max_tokens=1000)
        budget.consume(300)
        assert budget.spent == 300
        assert budget.remaining == 700

    def test_exhausted(self):
        budget = TokenBudgetManager(max_tokens=100)
        budget.consume(100)
        assert budget.exhausted is True


# ---------------------------------------------------------------------------
# ProjectIndex tests
# ---------------------------------------------------------------------------


class TestProjectIndex:
    def test_build_and_lookup(self):
        from codeguardian.parsers.base import ParsedFunction, ParsedStructure

        index = ProjectIndex()
        structures = {
            "src/service.py": ParsedStructure(
                functions=[
                    ParsedFunction(name="process", file_path="src/service.py",
                                   signature="def process(data: dict) -> bool",
                                   start_line=10, end_line=30, loc=20),
                    ParsedFunction(name="validate", file_path="src/service.py",
                                   signature="def validate(input: str) -> str",
                                   start_line=35, end_line=50, loc=15),
                ],
            ),
        }
        index.build_from_structures(structures)
        assert index.function_count == 2

        sigs = index.get_file_signatures("src/service.py")
        assert len(sigs) == 2
        assert "def process(data: dict) -> bool" in sigs


# ---------------------------------------------------------------------------
# ContextPackBuilder tests
# ---------------------------------------------------------------------------


class TestContextPackBuilder:
    def test_build_basic(self):
        index = ProjectIndex()
        builder = ContextPackBuilder(project_index=index)
        chunk = CodeChunk(
            file_path="app.py", source_code="def main(): pass",
            language="python", line_start=1, line_end=1,
            qualified_name="main",
        )
        pack = builder.build(chunk)
        assert pack.target_code == "def main(): pass"
        assert pack.file_path == "app.py"

    def test_build_with_local_findings(self):
        index = ProjectIndex()
        findings = {
            "app.py": [
                {"id": "SEC-001", "title": "SQL Injection", "severity": "high", "line_start": 5, "line_end": 5},
            ],
        }
        builder = ContextPackBuilder(project_index=index, local_findings=findings)
        chunk = CodeChunk(
            file_path="app.py", source_code="def query(): ...",
            language="python", line_start=1, line_end=10,
        )
        pack = builder.build(chunk)
        assert "SEC-001" in pack.local_findings_summary


# ---------------------------------------------------------------------------
# Prompt builder tests
# ---------------------------------------------------------------------------


class TestPromptBuilder:
    def test_build_review_prompt(self):
        pack = ContextPack(
            target_code="def foo(): return None",
            file_path="app.py",
            function_name="foo",
            line_start=1,
            line_end=1,
            language="python",
        )
        prompt = build_review_prompt(pack)
        assert "CodeGuardian" in prompt
        assert "app.py" in prompt
        assert "def foo(): return None" in prompt
        assert "检查清单" in prompt
        assert "自反思" in prompt
        assert "严格 JSON" in prompt


# ---------------------------------------------------------------------------
# AIReviewer tests
# ---------------------------------------------------------------------------


class TestAIReviewer:
    @pytest.mark.asyncio
    async def test_review_chunk_success(self):
        from codeguardian.ai.models import GenerateResult
        mock_provider = AsyncMock()
        mock_provider.generate_with_usage.return_value = GenerateResult(text=json.dumps({
            "findings": [
                {
                    "title": "Possible SQL Injection",
                    "category": "security",
                    "severity": "high",
                    "confidence": 8,
                    "line_start": 5,
                    "line_end": 5,
                    "description": "User input directly in query",
                    "evidence": "Line 5: query = f'SELECT * FROM {user_input}'",
                    "fix_suggestion": "Use parameterized queries",
                    "self_reflection": "No sanitization found in context",
                }
            ],
            "summary": "Found 1 security issue",
            "verified_local_findings": [],
        }))

        index = ProjectIndex()
        ctx_builder = ContextPackBuilder(project_index=index)
        budget = TokenBudgetManager(max_tokens=100000)
        reviewer = AIReviewer(mock_provider, ctx_builder, budget, max_concurrent=2)

        chunk = CodeChunk(
            file_path="app.py",
            source_code="query = f'SELECT * FROM {user_input}'",
            language="python",
            line_start=1,
            line_end=5,
        )
        results = await reviewer.review_chunks([chunk])
        assert len(results) == 1
        assert results[0].status == "done"
        assert len(results[0].findings) == 1
        assert results[0].findings[0].title == "Possible SQL Injection"

    @pytest.mark.asyncio
    async def test_review_chunk_json_parse_error(self):
        from codeguardian.ai.models import GenerateResult
        mock_provider = AsyncMock()
        mock_provider.generate_with_usage.return_value = GenerateResult(text="This is not JSON at all")

        index = ProjectIndex()
        ctx_builder = ContextPackBuilder(project_index=index)
        budget = TokenBudgetManager(max_tokens=100000)
        reviewer = AIReviewer(mock_provider, ctx_builder, budget)

        chunk = CodeChunk(
            file_path="bad.py", source_code="pass",
            language="python", line_start=1, line_end=1,
        )
        results = await reviewer.review_chunks([chunk])
        assert results[0].status == "failed"
        assert results[0].skip_reason == "parse_error"

    @pytest.mark.asyncio
    async def test_review_budget_exhausted(self):
        mock_provider = AsyncMock()
        index = ProjectIndex()
        ctx_builder = ContextPackBuilder(project_index=index)
        budget = TokenBudgetManager(max_tokens=0)  # Already exhausted

        reviewer = AIReviewer(mock_provider, ctx_builder, budget)

        chunk = CodeChunk(
            file_path="f.py", source_code="pass",
            language="python", line_start=1, line_end=1,
        )
        results = await reviewer.review_chunks([chunk])
        assert results[0].status == "skipped"
        assert results[0].skip_reason == "budget_exhausted"

    @pytest.mark.asyncio
    async def test_review_json_in_code_block(self):
        from codeguardian.ai.models import GenerateResult
        mock_provider = AsyncMock()
        mock_provider.generate_with_usage.return_value = GenerateResult(text=(
            "Here's my analysis:\n"
            "```json\n"
            '{"findings": [], "summary": "No issues", "verified_local_findings": []}\n'
            "```"
        ))

        index = ProjectIndex()
        ctx_builder = ContextPackBuilder(project_index=index)
        budget = TokenBudgetManager(max_tokens=100000)
        reviewer = AIReviewer(mock_provider, ctx_builder, budget)

        chunk = CodeChunk(
            file_path="clean.py", source_code="x = 1",
            language="python", line_start=1, line_end=1,
        )
        results = await reviewer.review_chunks([chunk])
        assert results[0].status == "done"
        assert len(results[0].findings) == 0
        assert results[0].summary == "No issues"


# ---------------------------------------------------------------------------
# ResultMerger tests
# ---------------------------------------------------------------------------


class TestResultMerger:
    def test_high_confidence_goes_to_primary(self):
        merger = ResultMerger(confidence_threshold=6)
        result = ReviewResult(
            chunk_file_path="a.py",
            findings=[
                AIFindingRaw(
                    title="Bug", category="logic", severity="high",
                    confidence=8, line_start=10, line_end=10,
                ),
            ],
            status="done",
        )
        output = merger.merge([result])
        assert len(output.primary) == 1
        assert len(output.supplementary) == 0

    def test_low_confidence_goes_to_supplementary(self):
        merger = ResultMerger(confidence_threshold=6)
        result = ReviewResult(
            chunk_file_path="a.py",
            findings=[
                AIFindingRaw(
                    title="Maybe", category="logic", severity="low",
                    confidence=4, line_start=10, line_end=10,
                ),
            ],
            status="done",
        )
        output = merger.merge([result])
        assert len(output.primary) == 0
        assert len(output.supplementary) == 1

    def test_very_low_confidence_discarded(self):
        merger = ResultMerger(confidence_threshold=6)
        result = ReviewResult(
            chunk_file_path="a.py",
            findings=[
                AIFindingRaw(
                    title="Noise", category="logic", severity="low",
                    confidence=2, line_start=10, line_end=10,
                ),
            ],
            status="done",
        )
        output = merger.merge([result])
        assert len(output.primary) == 0
        assert len(output.supplementary) == 0

    def test_confirmed_by_local_upgrades_existing(self):
        """When AI and local engine agree, upgrade the existing finding
        in-place instead of creating a duplicate."""
        existing = Finding(
            id="SEC-001", title="SQL Injection", category="security",
            severity=Severity.HIGH, confidence=Confidence.MEDIUM,
            location=Location(file_path="a.py", line_start=10),
            source_engine="security",
        )
        merger = ResultMerger(confidence_threshold=6, existing_findings=[existing])
        result = ReviewResult(
            chunk_file_path="a.py",
            findings=[
                AIFindingRaw(
                    title="SQL Injection", category="security", severity="high",
                    confidence=4, line_start=10, line_end=10,
                    description="Direct string concatenation in SQL query",
                    fix_suggestion="Use PreparedStatement with parameterized queries",
                ),
            ],
            status="done",
        )
        output = merger.merge([result])
        # No new finding created — existing one upgraded in-place
        assert len(output.primary) == 0
        assert len(output.supplementary) == 0
        # Existing finding is upgraded
        assert existing.confidence == Confidence.HIGH
        assert existing.evidence_level == "likely"
        assert "source:both" in existing.tags
        assert "AI 与本地规则" in existing.verification_summary
        # AI fix suggestion merged when local finding lacks one
        assert existing.fix_suggestion == "Use PreparedStatement with parameterized queries"

    def test_confirmed_by_local_keeps_existing_fix_suggestion(self):
        """When local finding already has fix_suggestion, AI suggestion is not overwritten."""
        existing = Finding(
            id="SEC-001", title="SQL Injection", category="security",
            severity=Severity.HIGH, confidence=Confidence.MEDIUM,
            location=Location(file_path="a.py", line_start=10),
            source_engine="security",
            fix_suggestion="Local rule remediation",
        )
        merger = ResultMerger(confidence_threshold=6, existing_findings=[existing])
        result = ReviewResult(
            chunk_file_path="a.py",
            findings=[
                AIFindingRaw(
                    title="SQL Injection", category="security", severity="high",
                    confidence=8, line_start=10, line_end=10,
                    fix_suggestion="AI suggestion",
                ),
            ],
            status="done",
        )
        output = merger.merge([result])
        assert len(output.primary) == 0
        # Original fix_suggestion preserved
        assert existing.fix_suggestion == "Local rule remediation"

    def test_skipped_chunks_counted(self):
        merger = ResultMerger(confidence_threshold=6)
        results = [
            ReviewResult.skipped("a.py", "rate_limit_exceeded"),
            ReviewResult.skipped("b.py", "api_unreachable"),
            ReviewResult(chunk_file_path="c.py", status="done"),
        ]
        output = merger.merge(results)
        assert output.total_chunks == 3
        assert output.done_chunks == 1
        assert output.skip_counts["rate_limit_exceeded"] == 1
        assert output.skip_counts["api_unreachable"] == 1

    def test_summary_line(self):
        output = MergeOutput(
            primary=[], supplementary=[],
            verified_local_finding_ids=[],
            total_chunks=10, done_chunks=8,
            skip_counts={"rate_limit_exceeded": 2},
        )
        line = output.summary_line
        assert "10 chunks" in line
        assert "8 完成" in line
        assert "2 rate_limit_exceeded" in line


# ---------------------------------------------------------------------------
# Config tests
# ---------------------------------------------------------------------------


class TestDeepReviewConfig:
    def test_default_values(self):
        config = DeepReviewConfig()
        assert config.enabled is True
        assert config.max_tokens_per_scan == 500_000
        assert config.max_concurrent == 5
        assert config.confidence_threshold == 6
        assert config.review_model == ""

    def test_app_config_has_deep_review(self):
        config = AppConfig()
        assert hasattr(config, "deep_review")
        assert isinstance(config.deep_review, DeepReviewConfig)

    def test_ai_config_defaults(self):
        config = AIConfig()
        assert config.provider == "openai"
        assert config.model == "gpt-4o"
        assert config.base_url is None


# ---------------------------------------------------------------------------
# Evidence model test
# ---------------------------------------------------------------------------


class TestAIReviewEvidence:
    def test_ai_review_evidence(self):
        evidence = AIReviewEvidence(
            content="SQL query built with string concatenation",
            file_path="service.py",
            line_start=42,
            ai_confidence=8,
            self_reflection="No input sanitization found",
            review_dimension="security",
        )
        assert evidence.type == "ai_review"
        assert evidence.ai_confidence == 8
        assert evidence.review_dimension == "security"


# ---------------------------------------------------------------------------
# ReviewResult helper tests
# ---------------------------------------------------------------------------


class TestReviewResult:
    def test_skipped_factory(self):
        result = ReviewResult.skipped("test.py", "budget_exhausted")
        assert result.status == "skipped"
        assert result.skip_reason == "budget_exhausted"
        assert result.chunk_file_path == "test.py"


# ---------------------------------------------------------------------------
# load_custom_rules test
# ---------------------------------------------------------------------------


class TestLoadCustomRules:
    def test_no_rules_file(self, tmp_path: Path):
        result = load_custom_rules(tmp_path)
        assert result == ""

    def test_with_rules_file(self, tmp_path: Path):
        rules_dir = tmp_path / ".codeguardian"
        rules_dir.mkdir()
        rules_file = rules_dir / "review_rules.yaml"
        rules_file.write_text(
            "rules:\n"
            "  - 'Use BigDecimal for money calculations'\n"
            "  - 'All user input must be validated'\n",
            encoding="utf-8",
        )
        result = load_custom_rules(tmp_path)
        assert "BigDecimal" in result
        assert "validated" in result


# ---------------------------------------------------------------------------
# ReviewCache TTL tests
# ---------------------------------------------------------------------------


class TestReviewCacheTTL:
    """Tests for the cache TTL / expiration mechanism."""

    def _make_chunk(self, code: str = "x = 1") -> CodeChunk:
        return CodeChunk(
            file_path="test.py",
            source_code=code,
            language="python",
            line_start=1,
            line_end=1,
        )

    def _make_result(self, chunk: CodeChunk) -> ReviewResult:
        return ReviewResult(
            chunk_file_path=chunk.file_path,
            chunk_qualified_name=chunk.qualified_name,
            findings=[],
            summary="ok",
            status="done",
        )

    def test_store_and_lookup_within_ttl(self, tmp_path: Path):
        """Fresh entries should be retrievable."""
        from codeguardian.ai.deep_review.cache import ReviewCache

        cache = ReviewCache(tmp_path, ttl_seconds=3600)
        chunk = self._make_chunk()
        result = self._make_result(chunk)
        cache.store(chunk, result)

        hit = cache.lookup(chunk)
        assert hit is not None
        assert hit.status == "done"

    def test_expired_entry_returns_none(self, tmp_path: Path):
        """Entries older than TTL should be treated as cache miss."""
        import time as _time
        from codeguardian.ai.deep_review.cache import ReviewCache, _chunk_cache_key

        cache = ReviewCache(tmp_path, ttl_seconds=10)
        chunk = self._make_chunk()
        result = self._make_result(chunk)
        cache.store(chunk, result)

        # Manually backdate the _created_at timestamp
        key = _chunk_cache_key(chunk)
        cache._store[key]["_created_at"] = _time.time() - 20

        hit = cache.lookup(chunk)
        assert hit is None
        # Expired entry should have been removed from store
        assert key not in cache._store


# ---------------------------------------------------------------------------
# UltraReviewer tests
# ---------------------------------------------------------------------------


class TestUltraReviewer:
    """Tests for the multi-dimensional explorer + critic pattern."""

    @pytest.mark.asyncio
    async def test_ultra_review_all_clean(self):
        """When no explorer finds issues, result should be clean."""
        from codeguardian.ai.deep_review.ultra_reviewer import UltraReviewer
        from codeguardian.ai.models import GenerateResult

        mock_provider = AsyncMock()
        # All explorers return no findings
        mock_provider.generate_with_usage.return_value = GenerateResult(
            text='{"findings": []}'
        )

        index = ProjectIndex()
        ctx_builder = ContextPackBuilder(project_index=index)
        budget = TokenBudgetManager(max_tokens=500_000)

        reviewer = UltraReviewer(
            provider=mock_provider,
            context_builder=ctx_builder,
            budget=budget,
            max_concurrent=3,
        )

        chunk = CodeChunk(
            file_path="clean.py",
            source_code="def hello(): return 'world'",
            language="python",
            line_start=1,
            line_end=1,
        )
        results = await reviewer.review_chunks([chunk])
        assert len(results) == 1
        assert results[0].status == "done"
        assert len(results[0].findings) == 0

    @pytest.mark.asyncio
    async def test_ultra_review_with_findings_and_critic(self):
        """Explorer finds issues, critic verifies some and rejects others."""
        from codeguardian.ai.deep_review.ultra_reviewer import UltraReviewer
        from codeguardian.ai.models import GenerateResult

        # Explorer returns findings; critic verifies 1 of 2
        call_count = 0

        async def mock_generate(prompt, system_message=None):
            nonlocal call_count
            call_count += 1
            # First 3 calls = explorers, 4th = critic
            if call_count <= 3:
                if "安全" in (system_message or ""):
                    return GenerateResult(text=json.dumps({
                        "findings": [{
                            "title": "SQL Injection",
                            "category": "security",
                            "severity": "high",
                            "confidence": 8,
                            "line_start": 5,
                            "line_end": 5,
                            "description": "Unsanitized input in query",
                            "evidence": "query = f'...'",
                            "fix_suggestion": "Use params",
                            "self_reflection": "No sanitization found",
                        }],
                    }))
                elif "逻辑" in (system_message or ""):
                    return GenerateResult(text=json.dumps({
                        "findings": [{
                            "title": "Possible None deref",
                            "category": "logic",
                            "severity": "medium",
                            "confidence": 4,
                            "line_start": 10,
                            "line_end": 10,
                            "description": "result might be None",
                            "evidence": "result.value",
                            "fix_suggestion": "Check None",
                            "self_reflection": "Caller might handle it",
                        }],
                    }))
                else:
                    return GenerateResult(text='{"findings": []}')
            else:
                # Critic: confirm SQL injection, reject None deref
                return GenerateResult(text=json.dumps({
                    "verified_findings": [{
                        "title": "SQL Injection",
                        "category": "security",
                        "severity": "high",
                        "confidence": 9,
                        "line_start": 5,
                        "line_end": 5,
                        "description": "Confirmed: unsanitized input",
                        "evidence": "query = f'...'",
                        "fix_suggestion": "Use parameterized query",
                        "self_reflection": "No framework protection",
                        "verdict": "confirm",
                    }],
                    "rejected": [{
                        "title": "Possible None deref",
                        "reason": "Caller validates input before this function",
                    }],
                    "summary": "1 confirmed, 1 rejected",
                }))

        mock_provider = AsyncMock()
        mock_provider.generate_with_usage = mock_generate

        index = ProjectIndex()
        ctx_builder = ContextPackBuilder(project_index=index)
        budget = TokenBudgetManager(max_tokens=500_000)

        reviewer = UltraReviewer(
            provider=mock_provider,
            context_builder=ctx_builder,
            budget=budget,
            max_concurrent=3,
        )

        chunk = CodeChunk(
            file_path="service.py",
            source_code="def query(user_input):\n    return db.execute(f'SELECT * FROM {user_input}')",
            language="python",
            line_start=1,
            line_end=10,
        )
        results = await reviewer.review_chunks([chunk])
        assert len(results) == 1
        assert results[0].status == "done"
        # Only 1 finding after critic filtering
        assert len(results[0].findings) == 1
        assert results[0].findings[0].title == "SQL Injection"
        assert results[0].findings[0].confidence == 9

    @pytest.mark.asyncio
    async def test_ultra_review_budget_exhausted(self):
        """Should skip when budget is exhausted."""
        from codeguardian.ai.deep_review.ultra_reviewer import UltraReviewer

        mock_provider = AsyncMock()
        index = ProjectIndex()
        ctx_builder = ContextPackBuilder(project_index=index)
        budget = TokenBudgetManager(max_tokens=0)  # Already exhausted

        reviewer = UltraReviewer(
            provider=mock_provider,
            context_builder=ctx_builder,
            budget=budget,
        )

        chunk = CodeChunk(
            file_path="f.py", source_code="pass",
            language="python", line_start=1, line_end=1,
        )
        results = await reviewer.review_chunks([chunk])
        assert results[0].status == "skipped"
        assert results[0].skip_reason == "budget_exhausted"

    @pytest.mark.asyncio
    async def test_ultra_review_critic_failure_fallback(self):
        """On critic failure, should fall back to all explorer findings."""
        from codeguardian.ai.deep_review.ultra_reviewer import UltraReviewer
        from codeguardian.ai.models import GenerateResult

        call_count = 0

        async def mock_generate(prompt, system_message=None):
            nonlocal call_count
            call_count += 1
            if call_count <= 3:
                # Only security explorer finds something
                if "安全" in (system_message or ""):
                    return GenerateResult(text=json.dumps({
                        "findings": [{
                            "title": "Hardcoded Secret",
                            "category": "security",
                            "severity": "high",
                            "confidence": 7,
                            "line_start": 1,
                            "line_end": 1,
                            "description": "API key in source",
                            "evidence": "key = 'sk-...'",
                            "fix_suggestion": "Use env var",
                            "self_reflection": "Clearly a secret",
                        }],
                    }))
                return GenerateResult(text='{"findings": []}')
            else:
                # Critic throws error
                raise RuntimeError("API timeout")

        mock_provider = AsyncMock()
        mock_provider.generate_with_usage = mock_generate

        index = ProjectIndex()
        ctx_builder = ContextPackBuilder(project_index=index)
        budget = TokenBudgetManager(max_tokens=500_000)

        reviewer = UltraReviewer(
            provider=mock_provider,
            context_builder=ctx_builder,
            budget=budget,
        )

        chunk = CodeChunk(
            file_path="config.py",
            source_code="API_KEY = 'sk-1234567890'",
            language="python",
            line_start=1,
            line_end=1,
        )
        results = await reviewer.review_chunks([chunk])
        assert results[0].status == "done"
        # Critic failed, so all explorer findings kept
        assert len(results[0].findings) == 1
        assert results[0].findings[0].title == "Hardcoded Secret"


class TestDeepReviewConfigUltra:
    """Test ultra review configuration fields."""

    def _make_chunk(self, code: str = "x = 1") -> CodeChunk:
        return CodeChunk(
            file_path="test.py",
            source_code=code,
            language="python",
            line_start=1,
            line_end=1,
        )

    def _make_result(self, chunk: CodeChunk) -> ReviewResult:
        return ReviewResult(
            chunk_file_path=chunk.file_path,
            chunk_qualified_name=chunk.qualified_name,
            findings=[],
            summary="ok",
            status="done",
        )

    def test_review_mode_default(self):
        config = DeepReviewConfig()
        assert config.review_mode == "standard"

    def test_review_mode_ultra(self):
        config = DeepReviewConfig(review_mode="ultra")
        assert config.review_mode == "ultra"

    def test_critic_model_default(self):
        config = DeepReviewConfig()
        assert config.critic_model == ""

    def test_evict_expired_on_load(self, tmp_path: Path):
        """Expired entries should be evicted when cache is loaded from disk."""
        import time as _time
        from codeguardian.ai.deep_review.cache import ReviewCache, _chunk_cache_key

        # Create a cache, store an entry, backdate it, save to disk
        cache = ReviewCache(tmp_path, ttl_seconds=10)
        chunk = self._make_chunk()
        result = self._make_result(chunk)
        cache.store(chunk, result)
        key = _chunk_cache_key(chunk)
        cache._store[key]["_created_at"] = _time.time() - 20
        cache.save()

        # Re-load — eviction should happen in __init__
        cache2 = ReviewCache(tmp_path, ttl_seconds=10)
        assert len(cache2) == 0

    def test_store_includes_created_at(self, tmp_path: Path):
        """Store should write a _created_at timestamp."""
        from codeguardian.ai.deep_review.cache import ReviewCache, _chunk_cache_key

        cache = ReviewCache(tmp_path)
        chunk = self._make_chunk()
        result = self._make_result(chunk)
        cache.store(chunk, result)

        key = _chunk_cache_key(chunk)
        assert "_created_at" in cache._store[key]
        assert isinstance(cache._store[key]["_created_at"], float)

    def test_save_and_reload_preserves_entries(self, tmp_path: Path):
        """Entries within TTL should survive save/reload."""
        from codeguardian.ai.deep_review.cache import ReviewCache

        cache = ReviewCache(tmp_path, ttl_seconds=3600)
        chunk = self._make_chunk("def hello(): pass")
        result = self._make_result(chunk)
        cache.store(chunk, result)
        cache.save()

        cache2 = ReviewCache(tmp_path, ttl_seconds=3600)
        assert len(cache2) == 1
        hit = cache2.lookup(chunk)
        assert hit is not None


# ---------------------------------------------------------------------------
# Config loader — TOML [ai.deep_review] extraction tests
# ---------------------------------------------------------------------------


class TestConfigLoaderDeepReview:
    """Tests for _merge_toml_into_config handling of [ai.deep_review]."""

    def test_nested_ai_deep_review_extracted(self):
        """[ai.deep_review] should be extracted to top-level deep_review."""
        from codeguardian.config.loader import _merge_toml_into_config

        data = {
            "ai": {
                "enabled": True,
                "provider": "openai",
                "deep_review": {
                    "review_model": "claude-opus-4-6",
                    "max_tokens_per_scan": 300_000,
                    "confidence_threshold": 7,
                },
            },
        }
        config = _merge_toml_into_config(data)
        assert config.deep_review.review_model == "claude-opus-4-6"
        assert config.deep_review.max_tokens_per_scan == 300_000
        assert config.deep_review.confidence_threshold == 7
        # ai section should not contain deep_review
        assert config.ai.enabled is True

    def test_top_level_deep_review_supported(self):
        """A standalone [deep_review] section should also work."""
        from codeguardian.config.loader import _merge_toml_into_config

        data = {
            "deep_review": {
                "max_concurrent": 3,
            },
        }
        config = _merge_toml_into_config(data)
        assert config.deep_review.max_concurrent == 3

    def test_top_level_overrides_nested(self):
        """If both exist, top-level [deep_review] wins (last-write)."""
        from codeguardian.config.loader import _merge_toml_into_config

        data = {
            "ai": {
                "deep_review": {
                    "max_concurrent": 10,
                },
            },
            "deep_review": {
                "max_concurrent": 2,
            },
        }
        config = _merge_toml_into_config(data)
        assert config.deep_review.max_concurrent == 2

    def test_defaults_when_no_deep_review(self):
        """If no deep_review section, defaults should apply."""
        from codeguardian.config.loader import _merge_toml_into_config

        data = {"ai": {"enabled": True}}
        config = _merge_toml_into_config(data)
        assert config.deep_review.max_tokens_per_scan == 500_000
        assert config.deep_review.confidence_threshold == 6


# ---------------------------------------------------------------------------
# Finding ID uniqueness tests
# ---------------------------------------------------------------------------


class TestFindingIdUniqueness:
    """Verifies that Finding IDs from AI merger don't collide."""

    def test_same_line_different_titles_unique_ids(self):
        """Two findings on the same file+line with different titles → different IDs."""
        merger = ResultMerger(confidence_threshold=6)
        result = ReviewResult(
            chunk_file_path="service.py",
            findings=[
                AIFindingRaw(
                    title="SQL Injection", category="security", severity="high",
                    confidence=8, line_start=42, line_end=42,
                ),
                AIFindingRaw(
                    title="Missing Input Validation", category="security", severity="medium",
                    confidence=7, line_start=42, line_end=42,
                ),
            ],
            status="done",
        )
        output = merger.merge([result])
        ids = [f.id for f in output.primary]
        assert len(ids) == 2
        assert ids[0] != ids[1], f"IDs should be unique but got: {ids}"

    def test_id_contains_hash_suffix(self):
        """Finding ID should contain a hash suffix for uniqueness."""
        merger = ResultMerger(confidence_threshold=6)
        result = ReviewResult(
            chunk_file_path="app.py",
            findings=[
                AIFindingRaw(
                    title="Bug", category="logic", severity="high",
                    confidence=8, line_start=10, line_end=10,
                ),
            ],
            status="done",
        )
        output = merger.merge([result])
        fid = output.primary[0].id
        # Should match pattern: AI-<filename>-L<line>-<8char_hash>
        assert fid.startswith("AI-app.py-L10-")
        assert len(fid.split("-")) >= 4  # at least 4 parts


# ---------------------------------------------------------------------------
# DeepReviewPipeline._assign_priorities — low-value finding filter (Plan A)
# ---------------------------------------------------------------------------


def _make_finding(file_path: str, category: str, line: int = 10) -> Finding:
    """Helper: build a minimal Finding with the given category."""
    return Finding(
        id=f"X-{category}-{line}",
        title=f"{category} issue",
        category=category,
        severity=Severity.MEDIUM,
        confidence=Confidence.HIGH,
        location=Location(file_path=file_path, line_start=line, line_end=line),
        source_engine="test",
    )


def _make_chunk(file_path: str) -> CodeChunk:
    """Helper: build a minimal CodeChunk with default P2 priority."""
    return CodeChunk(
        file_path=file_path,
        source_code="def f():\n    pass\n",
        language="python",
        line_start=1,
        line_end=2,
        priority=2,
    )


def _make_pipeline_skeleton() -> DeepReviewPipeline:
    """Build a DeepReviewPipeline without running its heavy __init__.

    `_assign_priorities` does not touch any instance attribute, so an
    uninitialised skeleton is sufficient and avoids spinning up
    TreeSitterManager / parser caches in unit tests.
    """
    return object.__new__(DeepReviewPipeline)


def _make_ctx(tmp_path: Path) -> ScanContext:
    return ScanContext(project_root=str(tmp_path), config=load_app_config(None))


class TestAssignPrioritiesLowValueFilter:
    """Plan A: low-value findings (maintainability/architecture) must NOT
    escalate their containing chunk to P0, since they are deterministic
    threshold-based outputs that don't benefit from LLM re-review."""

    def test_constant_covers_expected_categories(self):
        # Guard the contract that engines depend on. Adding/removing
        # a category here is a deliberate behaviour change.
        assert "maintainability" in LOW_VALUE_FINDING_CATEGORIES
        assert "architecture" in LOW_VALUE_FINDING_CATEGORIES
        # High-value categories must NOT be in the set.
        assert "security" not in LOW_VALUE_FINDING_CATEGORIES
        assert "defect" not in LOW_VALUE_FINDING_CATEGORIES
        assert "performance" not in LOW_VALUE_FINDING_CATEGORIES

    def test_maintainability_finding_does_not_escalate_to_p0(self, tmp_path):
        pipeline = _make_pipeline_skeleton()
        chunk = _make_chunk("src/foo.py")
        findings = [_make_finding("src/foo.py", "maintainability")]
        ctx = _make_ctx(tmp_path)

        pipeline._assign_priorities([chunk], findings, ctx)

        # Should fall back to default P2 (no other escalation signals)
        assert chunk.priority == 2

    def test_architecture_finding_does_not_escalate_to_p0(self, tmp_path):
        pipeline = _make_pipeline_skeleton()
        chunk = _make_chunk("src/foo.py")
        findings = [_make_finding("src/foo.py", "architecture")]
        ctx = _make_ctx(tmp_path)

        pipeline._assign_priorities([chunk], findings, ctx)

        assert chunk.priority == 2

    def test_security_finding_still_escalates_to_p0(self, tmp_path):
        pipeline = _make_pipeline_skeleton()
        chunk = _make_chunk("src/foo.py")
        findings = [_make_finding("src/foo.py", "security")]
        ctx = _make_ctx(tmp_path)

        pipeline._assign_priorities([chunk], findings, ctx)

        assert chunk.priority == 0

    def test_defect_finding_still_escalates_to_p0(self, tmp_path):
        pipeline = _make_pipeline_skeleton()
        chunk = _make_chunk("src/foo.py")
        findings = [_make_finding("src/foo.py", "defect")]
        ctx = _make_ctx(tmp_path)

        pipeline._assign_priorities([chunk], findings, ctx)

        assert chunk.priority == 0

    def test_mixed_categories_high_value_wins(self, tmp_path):
        """If a file has both maintainability and defect findings,
        the defect one still triggers P0 escalation."""
        pipeline = _make_pipeline_skeleton()
        chunk = _make_chunk("src/foo.py")
        findings = [
            _make_finding("src/foo.py", "maintainability", line=5),
            _make_finding("src/foo.py", "defect", line=20),
        ]
        ctx = _make_ctx(tmp_path)

        pipeline._assign_priorities([chunk], findings, ctx)

        assert chunk.priority == 0

    def test_only_low_value_findings_in_other_files_does_not_affect(self, tmp_path):
        """A maintainability finding in file A must not affect chunk in file B."""
        pipeline = _make_pipeline_skeleton()
        chunk_b = _make_chunk("src/b.py")
        findings = [_make_finding("src/a.py", "maintainability")]
        ctx = _make_ctx(tmp_path)

        pipeline._assign_priorities([chunk_b], findings, ctx)

        assert chunk_b.priority == 2

    def test_p0_set_by_chunker_is_preserved(self, tmp_path):
        """If chunker already marked a chunk P0 (e.g. changed lines),
        priority must NOT be downgraded by this pass."""
        pipeline = _make_pipeline_skeleton()
        chunk = _make_chunk("src/foo.py")
        chunk.priority = 0  # pre-set by chunker
        findings = [_make_finding("src/foo.py", "maintainability")]
        ctx = _make_ctx(tmp_path)

        pipeline._assign_priorities([chunk], findings, ctx)

        assert chunk.priority == 0


# ---------------------------------------------------------------------------
# Anti-hallucination defenses (regression tests for AI-WetestAPI-L264 case)
# ---------------------------------------------------------------------------


class TestMergerCategoryWhitelist:
    """ResultMerger must drop AI findings with categories outside the whitelist.

    Regression: previously a category like "syntax" silently fell back to
    "defect" and entered the report as a critical finding (e.g. AI claimed
    "retur should be return" — pure hallucination).
    """

    def test_unknown_category_finding_is_dropped(self):
        merger = ResultMerger(confidence_threshold=6)
        result = ReviewResult(
            chunk_file_path="a.py",
            findings=[
                AIFindingRaw(
                    title="Hallucinated syntax error",
                    category="syntax",  # NOT in whitelist
                    severity="critical",
                    confidence=9,
                    line_start=10, line_end=10,
                    evidence="代码中存在 'retur' 关键字",
                ),
            ],
            status="done",
        )
        output = merger.merge([result])
        assert output.primary == []
        assert output.supplementary == []

    def test_known_category_finding_kept(self):
        """Sanity: whitelisted categories still pass through."""
        merger = ResultMerger(confidence_threshold=6)
        result = ReviewResult(
            chunk_file_path="a.py",
            findings=[
                AIFindingRaw(
                    title="Real bug",
                    category="logic",
                    severity="high",
                    confidence=8,
                    line_start=10, line_end=10,
                ),
            ],
            status="done",
        )
        output = merger.merge([result])
        assert len(output.primary) == 1


class TestUltraNormalizeCategoryWhitelist:
    """ultra_reviewer._normalize_category must collapse out-of-spec categories
    to 'unknown' (which the merger then drops), instead of letting arbitrary
    strings through."""

    def test_invalid_category_becomes_unknown(self):
        from codeguardian.ai.deep_review.ultra_reviewer import _normalize_category
        assert _normalize_category("syntax") == "unknown"
        assert _normalize_category("style") == "unknown"
        assert _normalize_category("compile_error") == "unknown"
        assert _normalize_category("typo") == "unknown"

    def test_valid_categories_preserved(self):
        from codeguardian.ai.deep_review.ultra_reviewer import _normalize_category
        assert _normalize_category("security") == "security"
        assert _normalize_category("logic") == "logic"
        assert _normalize_category("null_safety") == "null_safety"
        assert _normalize_category("resource") == "resource"
        assert _normalize_category("error_handling") == "error_handling"
        assert _normalize_category("performance") == "performance"

    def test_chinese_aliases_preserved(self):
        from codeguardian.ai.deep_review.ultra_reviewer import _normalize_category
        assert _normalize_category("安全") == "security"
        assert _normalize_category("逻辑") == "logic"


class TestLocalValidatorEvidenceSubstring:
    """LocalValidator.\\_check_evidence_substring must reject findings whose
    evidence quotes a token absent from the source code (hallucination).

    Regression: AI claimed line 264 had keyword 'retur' but the source
    actually contained 'return'. This check kills that entire failure mode.
    """

    def _make_validator(self, tmp_path: Path, file_rel: str, content: str):
        from codeguardian.ai.deep_review.local_validator import LocalValidator
        target = tmp_path / file_rel
        target.parent.mkdir(parents=True, exist_ok=True)
        target.write_text(content, encoding="utf-8")
        return LocalValidator(tmp_path), file_rel

    def test_rejects_hallucinated_token_with_assertive_phrase(self, tmp_path):
        # Source has `return` on the flagged line; AI claims `retur` exists.
        source = "\n".join([
            "public class Foo {",                          # L1
            "    public int bar() {",                      # L2
            "        return 0;",                           # L3 ← target
            "    }",                                       # L4
            "}",                                           # L5
        ])
        validator, fp = self._make_validator(tmp_path, "Foo.java", source)
        finding = AIFindingRaw(
            title="语法错误",
            category="logic",  # whitelisted, would otherwise pass
            severity="critical",
            confidence=9,
            line_start=3, line_end=3,
            evidence="代码中存在关键字 'retur'，应该是 'return'",
        )
        kept, filtered = validator.filter_false_positives([finding], fp)
        assert kept == []
        assert filtered == [finding]

    def test_keeps_finding_when_token_actually_present(self, tmp_path):
        source = "\n".join([
            "public class Foo {",
            "    public int bar() {",
            "        return 0;",
            "    }",
            "}",
        ])
        validator, fp = self._make_validator(tmp_path, "Foo.java", source)
        # AI correctly references `return` which IS present.
        finding = AIFindingRaw(
            title="Real issue",
            category="logic",
            severity="medium",
            confidence=7,
            line_start=3, line_end=3,
            evidence="The 'return' statement should be wrapped in try/catch",
        )
        kept, filtered = validator.filter_false_positives([finding], fp)
        assert kept == [finding]
        assert filtered == []

    def test_no_assertive_phrase_no_substring_check(self, tmp_path):
        """Without assertive language, quoted tokens may legitimately
        reference symbols defined elsewhere — must not over-trigger."""
        source = "x = 1\n"
        validator, fp = self._make_validator(tmp_path, "a.py", source)
        finding = AIFindingRaw(
            title="Possible issue",
            category="logic",
            severity="low",
            confidence=5,
            line_start=1, line_end=1,
            # Mentions `SomeClass` which isn't in source, but no assertive
            # phrase like "代码中存在" — so we stay neutral.
            evidence="This may interact poorly with `SomeClass` defined upstream",
        )
        kept, filtered = validator.filter_false_positives([finding], fp)
        assert kept == [finding]
        assert filtered == []

    def test_rejects_when_any_asserted_token_missing(self, tmp_path):
        """If multiple tokens asserted, even one missing → reject."""
        source = "value = compute()\n"
        validator, fp = self._make_validator(tmp_path, "a.py", source)
        finding = AIFindingRaw(
            title="拼写错误",
            category="logic",
            severity="high",
            confidence=8,
            line_start=1, line_end=1,
            evidence="关键字 'valu' 应为 'value'",  # 'valu' missing, 'value' present
        )
        kept, filtered = validator.filter_false_positives([finding], fp)
        assert kept == []
        assert len(filtered) == 1


class TestPromptsHaveAntiHallucinationRules:
    """Sanity: every reviewer prompt must embed the anti-hallucination block."""

    def test_review_prompt_contains_rules(self):
        from codeguardian.ai.deep_review.context_builder import ContextPackBuilder  # noqa: F401
        from codeguardian.ai.prompts.deep_review import ANTI_HALLUCINATION_RULES, build_review_prompt
        ctx = ContextPack(
            target_code="x = 1\n",
            file_path="a.py", function_name="f",
            line_start=1, line_end=1, language="python",
        )
        prompt = build_review_prompt(ctx)
        assert "反幻觉硬约束" in prompt
        assert "禁止报告语法错误" in prompt
        # Cross-check the constant itself ships the key rules.
        assert "syntax" in ANTI_HALLUCINATION_RULES.lower() or "语法" in ANTI_HALLUCINATION_RULES

    def test_scout_prompt_contains_rules(self):
        from codeguardian.ai.prompts.deep_review import build_scout_prompt
        ctx = ContextPack(
            target_code="x = 1\n",
            file_path="a.py", function_name="f",
            line_start=1, line_end=1, language="python",
        )
        prompt = build_scout_prompt(ctx)
        assert "反幻觉硬约束" in prompt

    def test_explorer_and_critic_prompts_contain_rules(self):
        from codeguardian.ai.deep_review.ultra_reviewer import (
            CRITIC_PROMPT_TEMPLATE,
            EXPLORER_PROMPT_TEMPLATE,
        )
        # Explorer template uses {anti_hallucination} placeholder
        assert "{anti_hallucination}" in EXPLORER_PROMPT_TEMPLATE
        # Critic template hard-codes the rejection criteria
        assert "hallucinated_syntax_error" in CRITIC_PROMPT_TEMPLATE
        assert "hallucinated_evidence" in CRITIC_PROMPT_TEMPLATE
        assert "invalid_category" in CRITIC_PROMPT_TEMPLATE


# ---------------------------------------------------------------------------
# High-FP-mode local validator regression tests
#
# These cover the four most common AI false-positive patterns observed in
# real Java/Python codebases (spr_robot_java sample produced 60%+ FP rate
# from these alone before the fix):
#   1. Long-lived process-scoped clients reported as "resource leak"
#   2. Intentional fail-fast singleton (init+getInstance) reported as critical
#   3. while(true) + sleep worker loops reported as "infinite loop"
#   4. Generic "no null check" reported despite explicit guard on the variable
# ---------------------------------------------------------------------------


class TestLocalValidatorLongLivedResource:
    """resource-leak findings on process-scoped clients must be filtered."""

    def _make_validator(self, tmp_path: Path, file_rel: str, content: str):
        from codeguardian.ai.deep_review.local_validator import LocalValidator
        target = tmp_path / file_rel
        target.parent.mkdir(parents=True, exist_ok=True)
        target.write_text(content, encoding="utf-8")
        return LocalValidator(tmp_path), file_rel

    def test_okhttp_class_member_filtered(self, tmp_path):
        source = "\n".join([
            "public class WetestAPI {",                                # L1
            "    private final OkHttpClient okclient = new OkHttpClient();",  # L2 ← target
            "    public void doRequest() {",                            # L3
            "        okclient.newCall(req).execute();",                 # L4
            "    }",
            "}",
        ])
        validator, fp = self._make_validator(tmp_path, "WetestAPI.java", source)
        finding = AIFindingRaw(
            title="资源未关闭",
            category="resource",
            severity="high",
            confidence=8,
            line_start=2, line_end=2,
            evidence="OkHttpClient 创建后没有关闭",
        )
        kept, filtered = validator.filter_false_positives([finding], fp)
        assert kept == []
        assert filtered == [finding]

    def test_thread_pool_in_spring_component_filtered(self, tmp_path):
        source = "\n".join([
            "@Component",                                                   # L1
            "public class TaskRunner {",
            "    private final ExecutorService pool = Executors.newFixedThreadPool(10);",  # L3 ← target
            "    public void run() { pool.submit(task); }",
            "}",
        ])
        validator, fp = self._make_validator(tmp_path, "TaskRunner.java", source)
        finding = AIFindingRaw(
            title="ThreadPool 未关闭",
            category="resource",
            severity="high",
            confidence=7,
            line_start=3, line_end=3,
            evidence="Executors.newFixedThreadPool 创建后无 shutdown 调用",
        )
        kept, filtered = validator.filter_false_positives([finding], fp)
        assert kept == []
        assert filtered == [finding]

    def test_genuine_per_call_resource_leak_kept(self, tmp_path):
        """Per-method new of a Closeable WITHOUT close in following code
        should still pass through (real leak)."""
        source = "\n".join([
            "public class FooReader {",
            "    public String read(String path) {",
            "        FileInputStream fis = new FileInputStream(path);",  # L3 target
            "        return fis.read();",
            "    }",
            "}",
        ])
        validator, fp = self._make_validator(tmp_path, "FooReader.java", source)
        finding = AIFindingRaw(
            title="FileInputStream 未关闭",
            category="resource",
            severity="medium",
            confidence=7,
            line_start=3, line_end=3,
            evidence="FileInputStream 在方法内创建但未关闭",
        )
        kept, filtered = validator.filter_false_positives([finding], fp)
        # FileInputStream is NOT in the long-lived list, so check falls
        # through to _check_resource_close which sees no close → UNVERIFIED → kept.
        assert kept == [finding]
        assert filtered == []


class TestLocalValidatorIntentionalFailFast:
    """init()+getInstance()-throw fail-fast singleton must be filtered."""

    def _make_validator(self, tmp_path: Path, file_rel: str, content: str):
        from codeguardian.ai.deep_review.local_validator import LocalValidator
        target = tmp_path / file_rel
        target.parent.mkdir(parents=True, exist_ok=True)
        target.write_text(content, encoding="utf-8")
        return LocalValidator(tmp_path), file_rel

    def test_fail_fast_singleton_filtered(self, tmp_path):
        source = "\n".join([
            "public class SprClientAPI {",
            "    private static SprClientAPI sprClientAPI;",
            "    public static SprClientAPI getInstance() {",          # L3
            "        if (sprClientAPI == null) {",                     # L4
            "            throw new BizRuntimeException(\"not init\");",  # L5
            "        }",
            "        return sprClientAPI;",
            "    }",
            "    public static SprClientAPI init(String url, String code) {",
            "        sprClientAPI = new SprClientAPI(url, code);",
            "        return sprClientAPI;",
            "    }",
            "}",
        ])
        validator, fp = self._make_validator(tmp_path, "SprClientAPI.java", source)
        finding = AIFindingRaw(
            title="未初始化的单例实例",
            category="logic",
            severity="critical",
            confidence=8,
            line_start=3, line_end=3,
            evidence="getInstance 在 sprClientAPI 未初始化时抛 BizRuntimeException",
        )
        kept, filtered = validator.filter_false_positives([finding], fp)
        assert kept == []
        assert filtered == [finding]

    def test_non_singleton_class_not_affected(self, tmp_path):
        """A regular class without the init+getInstance pattern is untouched."""
        source = "public class OrderService {\n    public void process() { }\n}\n"
        validator, fp = self._make_validator(tmp_path, "OrderService.java", source)
        finding = AIFindingRaw(
            title="逻辑错误",
            category="logic",
            severity="medium",
            confidence=6,
            line_start=2, line_end=2,
            evidence="process 方法没有边界检查",
        )
        kept, filtered = validator.filter_false_positives([finding], fp)
        assert kept == [finding]
        assert filtered == []


class TestLocalValidatorIntentionalLoop:
    """while(true)+sleep worker loops must not be reported as infinite loop."""

    def _make_validator(self, tmp_path: Path, file_rel: str, content: str):
        from codeguardian.ai.deep_review.local_validator import LocalValidator
        target = tmp_path / file_rel
        target.parent.mkdir(parents=True, exist_ok=True)
        target.write_text(content, encoding="utf-8")
        return LocalValidator(tmp_path), file_rel

    def test_worker_loop_with_sleep_filtered(self, tmp_path):
        source = "\n".join([
            "public class NodeMgr {",
            "    public void runLoop() {",
            "        while (true) {",                          # L3 target
            "            doWork();",                           # L4
            "            Thread.sleep(1000);",                  # L5
            "        }",
            "    }",
            "}",
        ])
        validator, fp = self._make_validator(tmp_path, "NodeMgr.java", source)
        finding = AIFindingRaw(
            title="无限循环风险",
            category="logic",
            severity="high",
            confidence=7,
            line_start=3, line_end=3,
            evidence="while (true) 死循环可能导致线程阻塞",
        )
        kept, filtered = validator.filter_false_positives([finding], fp)
        assert kept == []
        assert filtered == [finding]

    def test_busy_loop_without_sleep_kept(self, tmp_path):
        """Real busy-loop (no sleep/wait/poll) must still be reported."""
        source = "\n".join([
            "public class Spinner {",
            "    public void spin(AtomicBoolean flag) {",
            "        while (!flag.get()) { }",                  # L3 target — busy spin
            "    }",
            "}",
        ])
        validator, fp = self._make_validator(tmp_path, "Spinner.java", source)
        finding = AIFindingRaw(
            title="busy-loop 无 sleep",
            category="performance",
            severity="medium",
            confidence=7,
            line_start=3, line_end=3,
            evidence="while 循环空转，未 sleep，会占满 CPU",
        )
        kept, filtered = validator.filter_false_positives([finding], fp)
        # Real busy-loop should NOT be filtered.
        assert kept == [finding]
        assert filtered == []


class TestLocalValidatorVariableSpecificNullGuard:
    """null_safety findings must check the *specific* variable's guard."""

    def _make_validator(self, tmp_path: Path, file_rel: str, content: str):
        from codeguardian.ai.deep_review.local_validator import LocalValidator
        target = tmp_path / file_rel
        target.parent.mkdir(parents=True, exist_ok=True)
        target.write_text(content, encoding="utf-8")
        return LocalValidator(tmp_path), file_rel

    def test_explicit_guard_for_named_variable_filters_finding(self, tmp_path):
        source = "\n".join([
            "public class MainTest {",
            "    public void run(Map<String, String> paramMap) {",
            "        if (paramMap.get(\"robotNum\") != null) {",   # L3
            "            int n = Integer.parseInt(paramMap.get(\"robotNum\"));",  # L4 target
            "        }",
            "    }",
            "}",
        ])
        validator, fp = self._make_validator(tmp_path, "MainTest.java", source)
        finding = AIFindingRaw(
            title="未检查 null",
            category="null_safety",
            severity="high",
            confidence=7,
            line_start=4, line_end=4,
            evidence="变量 paramMap 调用 .get() 后可能返回 null",
        )
        kept, filtered = validator.filter_false_positives([finding], fp)
        assert kept == []
        assert filtered == [finding]

    def test_fail_fast_throw_on_null_filters_finding(self, tmp_path):
        source = "\n".join([
            "public class Foo {",
            "    public void use(Bar bar) {",
            "        if (bar == null) throw new IllegalArgumentException();",  # L3 — fail fast
            "        bar.process();",                                         # L4 target
            "    }",
            "}",
        ])
        validator, fp = self._make_validator(tmp_path, "Foo.java", source)
        finding = AIFindingRaw(
            title="bar 可能为 null",
            category="null_safety",
            severity="high",
            confidence=8,
            line_start=4, line_end=4,
            evidence="变量 bar 在 L4 被调用 .process() 但未检查 null",
        )
        kept, filtered = validator.filter_false_positives([finding], fp)
        assert kept == []
        assert filtered == [finding]

    def test_no_guard_means_finding_kept(self, tmp_path):
        """No guard for the accused variable → finding should pass through."""
        source = "\n".join([
            "public class Foo {",
            "    public void use(Bar bar) {",
            "        bar.process();",                  # L3 target — no guard
            "    }",
            "}",
        ])
        validator, fp = self._make_validator(tmp_path, "Foo.java", source)
        finding = AIFindingRaw(
            title="bar 可能为 null",
            category="null_safety",
            severity="medium",
            confidence=6,
            line_start=3, line_end=3,
            evidence="变量 bar 直接调用 .process()，未检查 null",
        )
        kept, filtered = validator.filter_false_positives([finding], fp)
        assert kept == [finding]
        assert filtered == []


# ---------------------------------------------------------------------------
# Merger severity-cap regression tests
# ---------------------------------------------------------------------------


class TestMergerSeverityCap:
    """AI single-source findings must never reach CRITICAL; null_safety
    must not reach HIGH unless evidence shows actual dereference."""

    def test_ai_critical_capped_to_high(self):
        merger = ResultMerger(confidence_threshold=6)
        result = ReviewResult(
            chunk_file_path="a.py",
            findings=[
                AIFindingRaw(
                    title="Some Bug",
                    category="logic",
                    severity="critical",
                    confidence=8,
                    line_start=10, line_end=10,
                ),
            ],
            status="done",
        )
        output = merger.merge([result])
        assert len(output.primary) == 1
        assert output.primary[0].severity == Severity.HIGH

    def test_null_safety_high_without_dereference_evidence_capped_to_medium(self):
        merger = ResultMerger(confidence_threshold=6)
        result = ReviewResult(
            chunk_file_path="a.py",
            findings=[
                AIFindingRaw(
                    title="可能为 null",
                    category="null_safety",
                    severity="high",
                    confidence=7,
                    line_start=10, line_end=10,
                    evidence="变量 x 可能为 null",
                ),
            ],
            status="done",
        )
        output = merger.merge([result])
        assert len(output.primary) == 1
        assert output.primary[0].severity == Severity.MEDIUM

    def test_null_safety_high_with_npe_evidence_kept(self):
        merger = ResultMerger(confidence_threshold=6)
        result = ReviewResult(
            chunk_file_path="a.py",
            findings=[
                AIFindingRaw(
                    title="NPE 风险",
                    category="null_safety",
                    severity="high",
                    confidence=8,
                    line_start=10, line_end=10,
                    evidence="L10: x.method() 会触发 NullPointerException",
                ),
            ],
            status="done",
        )
        output = merger.merge([result])
        assert len(output.primary) == 1
        assert output.primary[0].severity == Severity.HIGH

    def test_confirmed_by_local_can_keep_high(self):
        """When local engine also finds the same issue, severity is preserved.
        The existing finding is upgraded in-place, not duplicated."""
        existing = Finding(
            id="SEC-001", title="SQL Injection", category="security",
            severity=Severity.HIGH, confidence=Confidence.MEDIUM,
            location=Location(file_path="a.py", line_start=10),
            source_engine="security",
        )
        merger = ResultMerger(confidence_threshold=6, existing_findings=[existing])
        result = ReviewResult(
            chunk_file_path="a.py",
            findings=[
                AIFindingRaw(
                    title="SQL Injection",
                    category="security",
                    severity="critical",  # AI says critical
                    confidence=9,
                    line_start=10, line_end=10,
                ),
            ],
            status="done",
        )
        output = merger.merge([result])
        # No new finding created — existing one upgraded in-place
        assert len(output.primary) == 0
        assert len(output.supplementary) == 0
        # Existing finding severity preserved (HIGH, not capped by AI single-source rule)
        assert existing.severity == Severity.HIGH
        assert existing.confidence == Confidence.HIGH
        assert "source:both" in existing.tags

