"""Ignore patterns — determines which files/directories to skip during scanning.

Ensures only developer-written project code is analyzed:
  - Skips third-party deps, vendored code, system libraries
  - Parses .gitignore for project-specific exclusions
  - Detects generated code (protobuf, thrift, graphql, openapi, etc.)
  - Detects binary files early to avoid wasted parse time
  - Supports glob/fnmatch patterns for user exclude_paths
"""

from __future__ import annotations

import fnmatch
import re
from functools import lru_cache
from pathlib import Path
from typing import Sequence

# Directories that should always be skipped during code analysis
DEFAULT_IGNORES = {
    ".git",
    ".svn",
    ".hg",
    ".idea",
    ".vscode",
    ".venv",
    "venv",
    "env",
    "__pycache__",
    ".pytest_cache",
    ".mypy_cache",
    ".ruff_cache",
    "node_modules",
    ".node_modules",
    "dist",
    "build",
    "target",
    "out",
    "bin",
    "obj",
    ".tox",
    ".nox",
    ".coverage",
    "htmlcov",
    ".cache",
    "reports",
    ".codeguardian",
    # Third-party / vendored / submodule directories
    "third_party",
    "thirdparty",
    "3rdparty",
    "vendor",
    "vendored",
    "external",
    "extern",
    "deps",
    "submodules",
    # Package manager caches
    ".npm",
    ".yarn",
    ".pnpm-store",
    "bower_components",
    ".gradle",
    ".m2",
    ".cargo",
    "pkg",
    # Runtime / SDK / system installation directories
    "jdk",
    "jre",
    "sdk",
    "runtime",
    "runtimes",
    # Documentation / assets (not developer code)
    "docs",
    "doc",
    "assets",
    "static",
    "public",
    "images",
    "fonts",
    "icons",
    # Test fixtures / snapshots (large generated data)
    "__snapshots__",
    "fixtures",
    "testdata",
    "test_data",
}

# Directory names that indicate SDK/system code when matched with prefix patterns.
_SDK_DIR_PREFIXES = (
    "jdk-", "jdk1", "jdk2",
    "jre-", "jre1", "jre2",
    "sdk-",
    "dotnet",
    "python2", "python3",
    "go1.",
    "node-v",
    "graalvm",
    "openjdk",
)

# Absolute-path patterns that indicate system/SDK installation roots (case-insensitive).
_SYSTEM_PATH_MARKERS = (
    "program files",
    "program files (x86)",
    "windows",
    "/usr/lib/",
    "/usr/local/lib/",
    "/usr/share/",
    "/opt/",
)

_GENERATED_DIR_MARKERS = {
    "generated",
    "generated-src",
    "generated-sources",
    "gensrc",
    "gen-go",
    "gen-py",
    "gen-java",
    "gen-cpp",
}

# Protobuf generated file suffixes
_PROTOBUF_FILE_SUFFIXES = (
    ".pb.go",
    ".pb.cc",
    ".pb.c",
    ".pb.h",
    ".pb.hpp",
    ".pb.m",
    ".pb.mm",
    ".pb.swift",
    ".pb.rs",
    "_pb2.py",
    "_pb2.pyi",
    "_pb2_grpc.py",
    ".pb.ts",
    ".pb.js",
)

# Thrift / gRPC / OpenAPI / GraphQL generated file patterns
_CODEGEN_FILE_SUFFIXES = (
    # Thrift
    "-remote.go",
    "_types.go",
    # gRPC gateway
    ".pb.gw.go",
    ".swagger.json",
    # Flatbuffers
    "_generated.h",
    "_generated.go",
    "_generated.rs",
)

_CODEGEN_FILE_PATTERNS = (
    # Thrift generated
    re.compile(r".*_(?:types|constants|service)\.(?:go|py|java|cpp|rb)$", re.IGNORECASE),
    # OpenAPI / Swagger generated
    re.compile(r".*(?:swagger|openapi)[-_].*\.(?:go|py|java|ts)$", re.IGNORECASE),
    # GraphQL generated
    re.compile(r".*\.generated\.(?:ts|tsx|js)$", re.IGNORECASE),
    re.compile(r".*\.graphql\.(?:ts|js)$", re.IGNORECASE),
)

_GENERATED_HEADER_RE = re.compile(
    r"generated by the protocol buffer compiler"
    r"|@@protoc_insertion_point"
    r"|<auto-generated"
    r"|@(?:javax\.annotation\.|jakarta\.annotation\.)?generated\b"
    r"|\bauto[- ]generated\b"
    r"|\bautomatically generated\b"
    r"|\bgenerated by (?:thrift|swagger|openapi|graphql)"
    r"|\bcode generated by"
    r"|\bthis file is @generated",
    re.IGNORECASE,
)

_DO_NOT_EDIT_RE = re.compile(r"\bdo not edit\b", re.IGNORECASE)
_PROTO_SOURCE_RE = re.compile(
    r"\bsource:\s+.+\.(?:proto|thrift|graphql|idl)\b", re.IGNORECASE
)

# Binary file detection: magic bytes for common formats
_BINARY_MAGIC = (
    b"\x7fELF",           # ELF
    b"MZ",               # PE/COFF
    b"\xca\xfe\xba\xbe", # Mach-O/Java class
    b"\xfe\xed\xfa",     # Mach-O
    b"\xcf\xfa\xed\xfe", # Mach-O 64
    b"PK\x03\x04",       # ZIP/JAR/APK
    b"\x1f\x8b",         # gzip
    b"BZh",              # bzip2
    b"\xfd7zXZ",         # xz
    b"\x89PNG",          # PNG
    b"\xff\xd8\xff",     # JPEG
    b"GIF8",             # GIF
    b"RIFF",             # RIFF (WAV, AVI)
    b"\x00\x00\x01\x00", # ICO
    b"SQLite format",    # SQLite
)

# Extensions that are always binary (skip without reading)
_BINARY_EXTENSIONS = frozenset({
    ".exe", ".dll", ".so", ".dylib", ".a", ".lib", ".o", ".obj",
    ".class", ".jar", ".war", ".ear",
    ".pyc", ".pyo", ".pyd",
    ".wasm",
    ".zip", ".tar", ".gz", ".bz2", ".xz", ".7z", ".rar",
    ".png", ".jpg", ".jpeg", ".gif", ".bmp", ".ico", ".svg", ".webp",
    ".mp3", ".mp4", ".avi", ".wav", ".flac", ".ogg", ".webm",
    ".pdf", ".doc", ".docx", ".xls", ".xlsx", ".ppt", ".pptx",
    ".ttf", ".otf", ".woff", ".woff2", ".eot",
    ".db", ".sqlite", ".sqlite3",
    ".bin", ".dat", ".raw",
    ".lock",  # package lock files (large, not source code)
})

# Non-code text files: static assets, docs, data templates, IDL.
# These carry no runtime logic; engines looking for bugs should never see them.
# NOTE: Config files (.json/.yaml/.toml/.ini/.env/...) are intentionally NOT here
# because config_risk_engine needs them when explicitly enabled.
_NON_CODE_EXTENSIONS = frozenset({
    # Documentation
    ".md", ".rst", ".txt", ".adoc",
    # Tabular data
    ".csv", ".tsv",
    # Web assets (markup/styling, no logic)
    ".html", ".htm", ".css", ".scss", ".sass", ".less",
    # IDL / schema definitions (generated code is the consumer, not the source of bugs)
    ".proto", ".graphql", ".gql", ".thrift", ".avsc", ".fbs",
    # Templates
    ".tmpl", ".tpl", ".mustache", ".hbs", ".handlebars", ".jinja", ".jinja2", ".j2", ".ejs",
})

# Module-level storage for user-configured exclude paths and gitignore patterns
_user_exclude_paths: list[str] = []
_gitignore_patterns: list[str] = []
_gitignore_loaded: bool = False
_gitignore_project_root: Path | None = None


def configure_exclude_paths(paths: Sequence[str]) -> None:
    """Set user-configured exclude paths (called once at startup from AppConfig)."""
    global _user_exclude_paths  # noqa: PLW0603
    _user_exclude_paths = list(paths)


def load_gitignore(project_root: Path) -> None:
    """Parse .gitignore from project root and load patterns.

    Supports standard gitignore syntax:
      - Comments (#), blank lines
      - Negation (!) — not fully supported, skipped
      - Directory-only patterns (trailing /)
      - Glob patterns (*, ?, **)
    """
    global _gitignore_patterns, _gitignore_loaded, _gitignore_project_root  # noqa: PLW0603
    _gitignore_project_root = project_root
    _gitignore_loaded = True
    _gitignore_patterns = []

    gitignore_path = project_root / ".gitignore"
    if not gitignore_path.is_file():
        return

    try:
        content = gitignore_path.read_text(encoding="utf-8", errors="ignore")
    except OSError:
        return

    for line in content.splitlines():
        line = line.strip()
        if not line or line.startswith("#"):
            continue
        if line.startswith("!"):
            # Negation patterns are complex; skip for now
            continue
        # Remove trailing slash (directory marker) — we match both
        pattern = line.rstrip("/")
        _gitignore_patterns.append(pattern)


def should_ignore(path: Path, *, project_root: Path | None = None) -> bool:
    """Check if a path should be excluded from analysis.

    Parameters
    ----------
    path : Path
        Relative or absolute file/directory path to check.
    project_root : Path | None
        If provided and gitignore not yet loaded, loads it.
    """
    # Auto-load gitignore on first call if project_root given
    global _gitignore_loaded  # noqa: PLW0603
    if not _gitignore_loaded and project_root is not None:
        load_gitignore(project_root)

    normalized_parts = {part.lower() for part in path.parts}

    # Check each part of the path against default ignores
    for part in normalized_parts:
        if part in DEFAULT_IGNORES:
            return True
        # Handle glob-like entries (e.g. *.egg-info)
        if part.endswith(".egg-info"):
            return True

    # Check SDK/runtime versioned directory prefixes
    for part in normalized_parts:
        if any(part.startswith(prefix) for prefix in _SDK_DIR_PREFIXES):
            return True

    # Check system installation paths (case-insensitive)
    path_str_lower = str(path).replace("\\", "/").lower()
    for marker in _SYSTEM_PATH_MARKERS:
        if marker in path_str_lower:
            return True

    # Check generated directory markers
    if normalized_parts & _GENERATED_DIR_MARKERS:
        return True

    # Check user-configured exclude paths (fnmatch glob patterns)
    if _user_exclude_paths:
        rel_str = str(path).replace("\\", "/")
        for exclude in _user_exclude_paths:
            normalized_exclude = exclude.replace("\\", "/").strip("/")
            if _matches_exclude_pattern(rel_str, normalized_exclude):
                return True

    # Check .gitignore patterns
    if _gitignore_patterns:
        rel_str = str(path).replace("\\", "/")
        if _matches_gitignore(rel_str):
            return True

    # Binary file extension check (fast path, no I/O)
    if path.suffix.lower() in _BINARY_EXTENSIONS:
        return True

    # Non-code text files (docs / static assets / templates / IDL).
    # Hard-excluded from all engines: these files carry no runtime logic
    # and produce no meaningful bug findings.
    if path.suffix.lower() in _NON_CODE_EXTENSIONS:
        return True

    # Generated file detection (requires file read for header check)
    if path.is_file() and _is_generated_source_file(path):
        return True

    # Skip hidden directories (starting with .) but not hidden files at project root
    for part in path.parts[:-1]:  # Check directory components only, not filename
        if part.startswith(".") and len(part) > 1:
            # Allow known CI/config directories
            if part in {".github", ".gitlab", ".circleci", ".husky"}:
                continue
            return True

    return False


def is_binary_file(path: Path) -> bool:
    """Quick binary file detection via extension and magic bytes."""
    if path.suffix.lower() in _BINARY_EXTENSIONS:
        return True
    # Read first 512 bytes to check for binary content
    try:
        with path.open("rb") as f:
            chunk = f.read(512)
    except OSError:
        return False
    if not chunk:
        return False
    # Check magic bytes
    for magic in _BINARY_MAGIC:
        if chunk.startswith(magic):
            return True
    # Check for null bytes (strong binary indicator)
    if b"\x00" in chunk:
        return True
    return False


def _matches_exclude_pattern(path_str: str, pattern: str) -> bool:
    """Match path against a single user exclude pattern using fnmatch/glob logic."""
    path_lower = path_str.lower()
    pattern_lower = pattern.lower()

    # If pattern contains glob chars, use fnmatch
    if any(c in pattern for c in "*?["):
        return fnmatch.fnmatch(path_lower, pattern_lower) or fnmatch.fnmatch(
            path_lower, f"*/{pattern_lower}"
        )

    # Otherwise match as exact directory segment
    segments = path_lower.split("/")
    return pattern_lower in segments


def _matches_gitignore(rel_path: str) -> bool:
    """Check if a relative path matches any loaded .gitignore pattern."""
    rel_lower = rel_path.lower()
    segments = rel_lower.split("/")

    for pattern in _gitignore_patterns:
        pat_lower = pattern.lower()

        # Pattern with slash = path relative to root
        if "/" in pat_lower:
            if fnmatch.fnmatch(rel_lower, pat_lower):
                return True
            if fnmatch.fnmatch(rel_lower, f"{pat_lower}/**"):
                return True
        else:
            # No slash = match any segment OR filename
            if any(c in pat_lower for c in "*?["):
                # Glob pattern: check against each segment and full path
                if fnmatch.fnmatch(rel_lower, f"**/{pat_lower}"):
                    return True
                if any(fnmatch.fnmatch(seg, pat_lower) for seg in segments):
                    return True
                # Also match filename
                if fnmatch.fnmatch(segments[-1] if segments else "", pat_lower):
                    return True
            else:
                # Exact name: match any directory segment
                if pat_lower in segments:
                    return True
    return False


@lru_cache(maxsize=32768)
def _is_generated_source_file(path: Path) -> bool:
    """Detect generated source files by suffix and header content."""
    lower_name = path.name.lower()

    # Fast suffix checks
    if lower_name.endswith(_PROTOBUF_FILE_SUFFIXES):
        return True
    if lower_name.endswith(_CODEGEN_FILE_SUFFIXES):
        return True

    # Pattern-based filename checks
    for pat in _CODEGEN_FILE_PATTERNS:
        if pat.match(lower_name):
            return True

    # Only check header for actual source files
    if path.suffix.lower() not in get_source_extensions():
        return False

    try:
        with path.open("r", encoding="utf-8", errors="ignore") as handle:
            header = handle.read(4096)
    except OSError:
        return False

    if not header:
        return False

    if _GENERATED_HEADER_RE.search(header):
        return True

    return bool(_DO_NOT_EDIT_RE.search(header) and _PROTO_SOURCE_RE.search(header))


def get_source_extensions() -> set[str]:
    """Return set of known source code extensions (developer-written code only).

    Excludes documentation, config, and asset files to avoid wasting
    AI tokens on non-code content.
    """
    return {
        # Python
        ".py", ".pyi", ".pyx",
        # JVM
        ".java", ".kt", ".scala", ".groovy",
        # JavaScript/TypeScript
        ".js", ".jsx", ".ts", ".tsx", ".mjs", ".cjs",
        # Systems
        ".go", ".rs", ".c", ".cpp", ".cc", ".cxx", ".h", ".hpp", ".cs",
        # Other languages
        ".rb", ".php", ".swift", ".dart", ".lua",
        ".r", ".m", ".sql", ".sh", ".bash", ".zsh", ".ps1",
        # Markup that contains logic
        ".vue", ".svelte",
    }


def get_config_extensions() -> set[str]:
    """Return set of config/infrastructure file extensions (for config_risk_engine)."""
    return {
        ".toml", ".yaml", ".yml", ".json", ".ini", ".cfg", ".conf",
        ".xml", ".properties",
        ".env", ".env.example",
        ".dockerfile", ".docker-compose.yml",
    }


def reset_state() -> None:
    """Reset module-level state (for testing)."""
    global _user_exclude_paths, _gitignore_patterns, _gitignore_loaded, _gitignore_project_root  # noqa: PLW0603
    _user_exclude_paths = []
    _gitignore_patterns = []
    _gitignore_loaded = False
    _gitignore_project_root = None
    _is_generated_source_file.cache_clear()
